### ISSUE TITLE
Need more information about install:

### ISSUE THREAD

**Issue by ateliershen** [mindkomm/timber-integration-woocommerce#1]
Hi,

Thank you for bringing this plugin!

It's quite embarrassing to ask, but where should I run `composer require mindkomm/timber-integration-woocommerce ` command? If I want to install as a plugin, do I have to compile by myself?

I tried to run in the root folder of my timber theme and inside the timber plugin folder, but this seems not working to both path.

It would be really nice if you can deliberate more about how to install 🙏Thank you!

**Comment by chrislind** [comment]
If you want to install it as a plugin you can simply download the github repository, and then run ```composer install``` the /timber-integration-woocommerce/ plugin folder

**Comment by gchtr** [comment]
Hey @ateliershen 

Never feel embarrassed for asking a question, even if it seems so simple ;).

I just figured out that it’s currently not possible to install it as a plugin without running Composer. The docs are not clear about that. I’ll see what I can do about this.

But in the meantime, you can:

- Go the way that @chrislind mentioned. In that case, you’d have to activate it in the plugins menu.
- Run `composer require mindkomm/timber-integration-woocommerce` inside your theme. In that case, you don’t have to activate it as a plugin.

(Sorry for closing this earlier, I accidentally clicked the wrong button)

**Comment by ateliershen** [comment]
Hi @gchtr @chrislind,

I have successfully installed and activated the integration as a plugin. Thank you for helping this out!
Tried almost every method [from here](https://github.com/timber/timber/issues/79) to add WooCommerce to my Timber theme, this might be the fastest way to do it.

Thank you again!
