### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Timber\LocationManager' not found

### ISSUE THREAD

**Issue by bradleyDouglas** [mindkomm/timber-integration-woocommerce#12]
Hello. I've never worked with WooCommerce before but build all my sites with Timber. When I found this integration I was really excited. However, I seem to be running into an error. 

For a simple test to see if everything was hooked up, I tried to call the featured products via a shortcode in a Gutenberg Block template (ACF Blocks). Before I installed this integration, that shortcode was displaying the featured products through that block.

Here's the complete error:

`Fatal error: Uncaught Error: Class 'Timber\LocationManager' not found in /app/public/wp-content/themes/roughhands/vendor/mindkomm/timber-integration-woocommerce/lib/Timber/Integrations/WooCommerce/WooCommerce.php:140 Stack trace: #0 /app/public/wp-includes/class-wp-hook.php(288): Timber\Integrations\WooCommerce\WooCommerce->maybe_render_twig_partial('/app/public/wp-...', 'loop/sale-flash...', Array) #1 /app/public/wp-includes/plugin.php(208): WP_Hook->apply_filters('/app/public/wp-...', Array) #2 /app/public/wp-content/plugins/woocommerce/includes/wc-core-functions.php(207): apply_filters('wc_get_template', '/app/public/wp-...', 'loop/sale-flash...', Array, '', '') #3 /app/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php(1242): wc_get_template('loop/sale-flash...') #4 /app/public/wp-includes/class-wp-hook.php(286): woocommerce_show_product_loop_sale_flash(Array) #5 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #6 /app/public/wp-includes/plugin.php(465): WP_Hook-> in /app/public/wp-content/themes/roughhands/vendor/mindkomm/timber-integration-woocommerce/lib/Timber/Integrations/WooCommerce/WooCommerce.php on line 140`

Any help is much appreciated!

**Comment by gchtr** [comment]
Hey @bradleyDouglas 

It seems like [Timber](https://github.com/timber/timber) itself can’t be found. Did you install it as well?

**Comment by bradleyDouglas** [comment]
@gchtr I have Timber installed, but I ddin't install it via Composer... I wonder if that's what cause my issues.

**Comment by gchtr** [comment]
Okay then, so you installed it as a plugin. Can you share some code for how you’ve set up the custom ACF Block for Gutenberg so I can try and reproduce the error?

**Comment by bradleyDouglas** [comment]
Here's how I registered the block.
```
acf_register_block(array(
	'name'				=> 'featured-products-block',
	'title'				=> __( 'Featured Products', 'your-text-domain' ),
	'description'		        => __( 'Block to show case 4 featured products', 'your-text-domain' ),
	'render_callback'	        => 'my_acf_block_render_callback',
	'category'			=> 'layout',
	'icon'				=> 'format-image',
         'keywords'		        => array( 'featured' ),
) );
```

**Comment by gchtr** [comment]
Hey @bradleyDouglas! Sorry for answering so late. I hope this bug isn’t still bothering you.

Unfortunately I couldn’t reproduce your issue. I’ve set up an ACF block that displays the featured with and added it to a normal page. Everything works fine, no errors. Here’s the code I used:

```php
function my_acf_block_render_callback( $block, $content = '', $is_preview = false, $post_id = null ) {
	echo do_shortcode( '[featured_products]' );
}

add_action( 'acf/init', 'my_acf_init_block_types' );
function my_acf_init_block_types() {
	// Check function exists.
	if ( function_exists( 'acf_register_block_type' ) ) {
		acf_register_block( array(
			'name'            => 'featured-products-block',
			'title'           => __( 'Featured Products', 'your-text-domain' ),
			'description'     => __( 'Block to show case 4 featured products', 'your-text-domain' ),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'layout',
			'icon'            => 'format-image',
			'keywords'        => array( 'featured' ),
		) );
	}
}
```

Where exactly did you add your block? Was it on a special page?

Where and how do you call `new Timber\Timber();`?

Maybe you could try and [install Timber through Composer](https://timber.github.io/docs/getting-started/setup/#via-github-for-developers) instead of installing it as a plugin so we can make sure it’s not a compatibility problem with the plugin version?

**Comment by gchtr** [comment]
Closed for inactivity.
