### ISSUE TITLE
Wrong products thumbnails in upsells

### ISSUE THREAD

**Issue by tameroski** [mindkomm/timber-integration-woocommerce#17]
Hi !

I have an issue with the upsells products list on the single product page : the current product image is displayed for each upsell, instead of the upsell product image itself.

The upsell name & link are correct. 

I tried to disable every piece of custom code i have but still got the same issue.

Any hints ?

Thanks

**Comment by gchtr** [comment]
Did you already check out the newest [release candidate](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.6.0-rc.1) for this integration? Because it might be that is already resolved with that. You should be able to get it with

```bash
composer require mindkomm/timber-integration-woocommerce:0.6.0-rc.1
```

Otherwise, I might have to investigate further. In that case, it would help if you could post some Twig code from your singular product page that I could use to replicate the problem.

**Comment by tameroski** [comment]
Hi Lukas,

I'm already on the last release.

I rolled back to your default twig files and still got the issue. 

Also rolled back to the very minimum in functions.php : 
```php
<?php
WooCommerce::init();
add_action( 'after_setup_theme', function() {
    add_theme_support( 'woocommerce' );
} );
```
Also removed everything in my woocommerce.php : 

```php
<?php
Timber\Integrations\WooCommerce\WooCommerce::render_default_template();
```
And still got the issue ☹️

I just have several upsells associated to products, and they all have the main product thumbnail showing instead of their own thumbnail 🤷‍♂️ 

EDIT : didn't notice, but prices and add to cart link are also all the same ! Name and link to product are OK.

<img width="1502" alt="Capture d’écran 2020-11-26 à 09 07 20" src="https://user-images.githubusercontent.com/338432/100324020-e790f900-2fc6-11eb-9e28-32b0e639ba15.png">

**Comment by ffaltin** [comment]
Hi,

I got the same issue and found a solution.

In line 249 from lib/WooCommerce.php : 

`global $product, $post;

			if ( ! $product ) {
				$product = wc_setup_product_data( $post );
			}`

The product ID remains the same in single-product page but not the post ID.

I fixed it by adding a condition:

`
if ( ! $product || $product->get_id() != $post->ID) {
			$product = wc_setup_product_data( $post );
		}
`

I'll do a pull request to fix the issue soon ;)

**Comment by tameroski** [comment]
The problem is that some templates like up-sells.php set data using a good old `setup_postdata` :

```php
<?php woocommerce_product_loop_start(); ?>

    <?php foreach ( $upsells as $upsell ) : ?>

        <?php
		 $post_object = get_post( $upsell->get_id() );

		 setup_postdata( $GLOBALS['post'] =& $post_object ); // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited, Squiz.PHP.DisallowMultipleAssignments.Found

		 wc_get_template_part( 'content', 'product' );
	 ?>
     
    <?php endforeach; ?>

<?php woocommerce_product_loop_end(); ?>
```

Adding something like this will fix the issue: 
```php
setup_postdata( $GLOBALS['product'] = wc_setup_product_data( $post_object ) );
```

But i don't see (yet) how this can be done properly within your package.

**Comment by gchtr** [comment]
Okay, thanks for your research. I will have to investigate further what the best solution for this would be.

In the meantime, does it work if you use a Twig file for the up-sells?

**views/woocommerce/single-product/up-sells.twig**

```twig
{% if wc.upsells  %}
	{{ fn('woocommerce_product_loop_start') }}

    {% for post in wc.upsells %}
        {{ include('woocommerce/content-product.twig', {
            product: post.product
        }) }}
    {% endfor %}

    {{ fn('woocommerce_product_loop_end') }}

	{# Not sure if this is needed as well, currently. #}
    {{ fn('wp_reset_postdata') }}
{% endif %}
```

**Comment by tameroski** [comment]
It does !

Thanks for the workaround

**Comment by gchtr** [comment]
Hey @tameroski

I looked at the problem more closely and I think I found a solution that should solve cases like this, when obviously the product global is not working correctly. I added it as a pre-release in [0.6.1-rc.1](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.6.1-rc.1), because I want to test it out a bit more myself.

I’d be glad if you could check it out and see if that fixes the problem :).

**Comment by gchtr** [comment]
Closing this, because the updates in [0.6.1](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.6.1) and [0.7.1](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.7.1) should fix this.
