### ISSUE TITLE
Product Twig Function not available when using admin-ajax.php

### ISSUE THREAD

**Issue by ahbyass** [mindkomm/timber-integration-woocommerce#19]
When getting posts via ajax with admin-ajax

Timber\Integrations\WooCommerce\WooCommerce does not init.

Specifically highlighted when trying to use Product Twig Function.

Fixed by changing line 55 

		if ( is_admin() && ! wp_doing_ajax() ) {
			return;
		}

**Comment by gchtr** [comment]
Sorry for the late reply. I just realized that this is the same issue as #22. This is fixed in the [0.6.0 release](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.6.0).
