### ISSUE TITLE
`wc.upsells` only has a single item, even when I've added more than one.

### ISSUE THREAD

**Issue by amazingrando** [mindkomm/timber-integration-woocommerce#26]
# Problem
When I create a new Woocommerce product with two or more upsells, only one upsell shows.

# My setup
* php:7.4
* All plugins and up to date
* "mindkomm/timber-integration-woocommerce": "0.6.1-rc.1"
  * also happens when I rollback to 0.6.0.

Please note that my PHP skills aren't strong.

I would appreciate any help that anyone could give. **I'm sure more information is needed and if you tell me what you need, I'm happy to provide it.**

Thank you.

**Comment by gchtr** [comment]
Hey @amazingrando

Do you still have that problem with [the latest version](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.7.2)?

**Comment by amazingrando** [comment]
@gchtr I've handed this project over to another developer team, so I'm not certain about the status. I will close this issue.
