### ISSUE TITLE
Uncaught Error: Class 'Timber\Integrations\WooCommerce\WooCommerce' not found

### ISSUE THREAD

**Issue by countfak** [mindkomm/timber-integration-woocommerce#27]
Hi, I'm getting this error. All I did was installing the integration with Composer.

`Uncaught Error: Class 'Timber\Integrations\WooCommerce\WooCommerce' not found`

I'm using Timber 2.0.0-alpha.3 (maybe that's the problem?), installed with Composer as well.

**Comment by gene-roussetos** [comment]
@countfak this should not be an issue as it's just a namespace and it matches the latest release for this integration https://github.com/mindkomm/timber-integration-woocommerce/blob/0.6.0/lib/WooCommerce.php

namespace: `Timber\Integrations\WooCommerce`
class name: `WooCommerce`

Check your vendor folder to validate the integration is installed
Then perform a `composer dump-autoload` and reload your php cache mechanism if you use any? (like php-fpm)

These actions should sort it out

**Comment by RoussKS** [comment]
@countfak this should not be an issue as it's just a namespace and it matches the latest release for this integration https://github.com/mindkomm/timber-integration-woocommerce/blob/0.6.0/lib/WooCommerce.php

namespace: `Timber\Integrations\WooCommerce`
class name: `WooCommerce`

Check your vendor folder to validate the integration is installed
Then perform a `composer dump-autoload` and reload your php cache mechanism if you use any? (like php-fpm)

These actions should sort it out

**Comment by countfak** [comment]
Hi @RoussKS thanks for your reply.
I'm not working on that project anymore so unfortunately I'm not able to try your solution, sorry.
You can consider this closed, maybe it will be helpful for someone else in the future.
Thanks again.
