### ISSUE TITLE
PHP 8.0 support?

### ISSUE THREAD

**Issue by mark-alexandre** [mindkomm/timber-integration-woocommerce#28]
Hi there,

When do you plan to update your package to be PHP 8 compatible? The problem I'm facing is in the platform requirements which is only PHP 7.*, when I hope it was PHP 7.* || PHP 8.*

**Comment by gchtr** [comment]
Sorry for letting you wait for so long.

I updated it in the latest release: https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.7.0.
