### ISSUE TITLE
Clean up few things

### ISSUE THREAD

**Issue by szepeviktor** [mindkomm/timber-integration-woocommerce#30]
Add license file

Update repo description (About ⚙️) "WooCommerce integration for Timber"
untick "Packages"

Fix typos
lib/Product.php:71: Mimick ==> Mimic
lib/WooCommerce.php:347: mimicks ==> mimics

Add timber/timber as dependency

```diff
diff --git a/lib/WooCommerce.php b/lib/WooCommerce.php
index 24c30eb..cb3f5b2 100644
--- a/lib/WooCommerce.php
+++ b/lib/WooCommerce.php
@@ -82,7 +82,7 @@ class WooCommerce {
                // Add WooCommerce context data to normal context.
                add_filter( 'timber/context', array( $self, 'get_woocommerce_context' ) );

-               add_action( 'timber/twig/functions', array( $self, 'add_timber_functions' ) );
+               add_filter( 'timber/twig/functions', array( $self, 'add_timber_functions' ) );
        }

        /**
@@ -445,7 +445,7 @@ class WooCommerce {
        /**
         * Make function available in Twig.
         *
-        * @param \Twig_Environment $twig Twig Environment.
+        * @param \Twig\Environment $twig Twig environment.
         *
         * @return mixed
         */
```

clean up exported files
`git archive HEAD | tar --list --exclude="lib" --exclude="lib/*"`

move TODO-s from source code and README into GitHub issues

@gchtr What do you think?

**Comment by szepeviktor** [comment]
... and maybe https://github.com/DavidAnson/markdownlint-cli2
`.markdownlint-cli2.yaml`
```yaml
config:
    # Break lines later
    line-length: false
```

**Comment by gchtr** [comment]
Thanks, Viktor, I’ll have a look at these.
But first, I’ll continue working on the testing setup (no help there needed just yet 😊).

**Comment by szepeviktor** [comment]
For testing there is https://github.com/Automattic/wordbless

**Comment by gchtr** [comment]
The relevant issues are fixed. Thanks again for your suggestions, Viktor!

**Comment by szepeviktor** [comment]
Glad to contribute.
