### ISSUE TITLE
Integration for Timber 2.0

### ISSUE THREAD

**Issue by beiermarco** [mindkomm/timber-integration-woocommerce#34]
Hey!

First of all - i appreciate the effort you put into developing this extension!

Since Timber v2 is close to release and offers numerous improvements, I'm curious about any plans to update the extension to be compatible with the new version.

Thanks in advance!

**Comment by svenvonarx** [comment]
Is it possible to get any updates here? I'm currently trying to make our theme Timber 2.0 ready and we used this package for the WooCommerce Integration. Now i wonder if packages like that get completely replaced by default functionality of Timber 2.0 or if they will see updates at some point?

**Comment by gchtr** [comment]
I was working on an update in the last couple of weeks and I now got an alpha release ready: https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/1.0.0-alpha.1.

I’d be happy if you could test it out and report if something doesn’t work.

There’s quite a few things that I could remove, because they are now handled by Timber itself. But it still makes sense to use the integration.

**Comment by svenvonarx** [comment]
Thank you so much for your quick response. I'll try to implement it and play around with it as much as I can.

**Comment by svenvonarx** [comment]
Hey @gchtr 
I played around a bit and encountered an error in the single product handling.

![image](https://github.com/mindkomm/timber-integration-woocommerce/assets/5146747/3c1d450b-ccd9-477d-9e8d-a94da3c42573)

Somehow the post in context gets set to null in the dump screenshot below. This only happens with the Timber classmap hooked in the Screenshot above. I didn't check this functionality in Timber 2.0 yet - but might be a hint for you.
It didn't help to play around with the priority of the timber context aswell. The only way for me to get the template to work is by adding ['post' => Timber::get_post()] at the render_default_template call.

![image](https://github.com/mindkomm/timber-integration-woocommerce/assets/5146747/02ede061-d69c-434d-8ea9-a26b4252b3f2)

Letting you know if I find out more.

**Comment by cafesk8** [comment]
@gchtr - Can confirm the same behaviour as @svenvonarx above. Fixed by adding this to **woocommerce.php**

```
use Timber\Integrations\WooCommerce\WooCommerce;

$context = [
    'post'      => Timber::get_post()
];

WooCommerce::render_default_template( $context );
```

**Comment by gchtr** [comment]
@svenvonarx @cafesk8 Thanks for testing it out and providing info about the error. I’ve found and fixed it now.

Check out the new release to test it: https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/1.0.0-rc.1.

**Comment by svenvonarx** [comment]
@gchtr Thank you so much for the fix/update! I'll try to test it further this week.

**Comment by svenvonarx** [comment]
@gchtr After playing around with the integration I couldn't find any errors anymore. We will see more as soon as we start setting up a first project with it.

**Comment by gchtr** [comment]
The 1.0.0 release is out: https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/1.0.0
