### ISSUE TITLE
Related products - passing parent product ID

### ISSUE THREAD

**Issue by emcubio** [mindkomm/timber-integration-woocommerce#35]
Hi guys, at the start I very appreciate this project. It's awesome!

In examples you show this code at **views/woocommerce/single-product/related.twig**:
```
<?php foreach ( $related_products as $related_product ) : ?>
    <?php
        $post_object = get_post( $related_product->get_id() );

        setup_postdata( $GLOBALS['post'] =& $post_object );
        
        wc_get_template_part( 'content', 'product' );
    ?>
<?php endforeach; ?>
```
Replaced with
```
{% for post in wc.related_products %}
    {{ fn('wc_get_template_part', 'content', 'product' ) }}
{% endfor %}
```
If you try it, in product detail it work's correct? If I look at related products, there are wrong data. Image, price and rating in all related products is inherited from main product.
After debugging loop displayed above I found that in file **WooCommerce.php** function **maybe_render_twig_template_part** stores in variable **global $product** currently displayed product, in **global $post** current related product's post. They are different, but code below passes to the context data based on global **$product** variable, which is currently displayed product. 
```
if ( $product instanceof \WC_Product ) {
	$context['product'] = $product;
	$context['post_id'] = $product->get_id();
	$context['post']    = Timber::get_post( $product->get_id() );
}
```
If you can test it, please look at it, if it works correct.
Iny my case, I fixed it with getting product from current post, if global post and product ID's differ, for such cases:
```
// Add current product to context.
if ( $product instanceof \WC_Product ) {
	$context['product'] = $product;
	$context['post_id'] = $product->get_id();
	$context['post']    = Timber::get_post( $product->get_id() );
}
// MOD - Fix related.twig - there was passed parent product ID for related products
if($post->id !== $product->get_ID()){
	$context['product'] = wc_setup_product_data( $post );
	$context['post_id'] = $post->ID;
	$context['post']    = Timber::get_post( $post->ID );
}
```
Currently not tested at whole project, if are there some places where should be that ID's different.
Thank you for feedback.

**Comment by gchtr** [comment]
Could you check whether you still run into that issue with the new version that is compatible with Timber v2?

https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/1.0.0-rc.1

**Comment by gchtr** [comment]
Closing this, because we didn’t get any feedback.
