### ISSUE TITLE
Documentation needs updating for 1.0.0

### ISSUE THREAD

**Issue by standerksen** [mindkomm/timber-integration-woocommerce#40]
See title.

**Comment by gchtr** [comment]
@standerksen Can you check again?

The default branch of the repository was not on 1.x, but it is now.

**Comment by standerksen** [comment]
Thank you for your reply. The links in the README file seem to be linking to different files than those in the docs folder of the 1.x branch, is that correct?

**Comment by gchtr** [comment]
Oooh, yeah I missed that. Thanks for the hint. I fixed it just now.
