### ISSUE TITLE
FatalError since Timber version 2.2.0

### ISSUE THREAD

**Issue by blayce-standerksen** [mindkomm/timber-integration-woocommerce#41]
I have recently updated my Timber from 2.1.0 to 2.2.0, and in doing so it gives me the following error on product pages:

FatalError: 
```
Compile Error: Declaration of Timber\Integrations\WooCommerce\Product::build(WP_Post $wp_post):
Timber\Integrations\WooCommerce\Product must be compatible with Timber\Post::build(WP_Post $wp_post):
Symfony\Component\ErrorHandler\DebugClassLoader
```

The related line is: `mindkomm\timber-integration-woocommerce\lib\Product.php:40`

**Comment by gchtr** [comment]
Can you check whether the latest release https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/1.0.1 fixes your issue?

**Comment by blayce-standerksen** [comment]
That is one fast response! 😮 It fixed the issue, thanks!
