### ISSUE TITLE
Documentation v1.x outdated

### ISSUE THREAD

**Issue by stephanecw** [mindkomm/timber-integration-woocommerce#43]
Hi,
Thank you for this awesome package. I've been using it for many years.
However I noticed few things that could be updated in v1.x version :

An error with this hook :

```php
add_filter( 'timber/woocommerce/views_folder', function( $subfolder ) {
    return 'woo';
} );
```

The correct hook is : 

```php
add_filter( 'theme/woocommerce/views_folder', function( $subfolder ) {
    return 'woo';
} );
```

In the helper class init() method I think you could replace :

```php
if ( class_exists( 'WooCommerce' ) ) {
            \Timber\Integrations\WooCommerce\WooCommerce::init();
 }
```

by

```php
add_filter( 'timber/integrations', function ( array $integrations ): array {
    $integrations[] = new \Timber\Integrations\WooCommerce\WooCommerceIntegration();

    return $integrations;
} );
```

According to the install documentation.

**Comment by gchtr** [comment]
Hey @stephanecw 

Thanks for your issue.

In fact, the `theme/woocommerce/views_folder` is named wrongly in the code, but named correctly in the documentation. It should be named `timber/woocommerce/views_folder`. I added the `timber/woocommerce/views_folder` filter (https://github.com/mindkomm/timber-integration-woocommerce/commit/4c0222cc6376f174f61113a8cf233f91eda1ff18). The `theme/woocommerce/views_folder` filter will be deprecated with a next major version.

And thanks for the hint about the documentation. I added a fix for that in #45.

Both fixes are released in https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/v1.1.0.
